FROM kennethreitz/pipenv

RUN apt-get -y update
RUN apt-get -y install build-essential python3-dev python3-cffi \
    libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 \
    libffi-dev shared-mime-info curl

RUN mkdir -p ~/.local/share/fonts
RUN curl -L https://fonts.google.com/download?family=Cormorant%20Garamond -o Cormorant_Garamond.zip
RUN unzip Cormorant_Garamond.zip
RUN mv *.ttf ~/.local/share/fonts
RUN fc-cache -f
ADD . /app
RUN pipenv install --system --dev

WORKDIR /app

CMD pytest -p no:warnings test_title_page.py
