version: "3"
services:
  app:
    image: rickh94/title-page:19.10.11
    volumes:
      - completions:/completions
    tmpfs:
      - /srv/media
    restart: always
    networks:
      - titlepage
    ports:
      - "8080:80"

networks:
  titlepage:

volumes:
  completions:
