version: "3"
services:
  app:
    build:
      context: app
    volumes:
      - ./app:/app
    tmpfs:
      - /srv/media
    ports:
      - "8080:80"
    restart: always


networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.91.0/24
