version: "3"
services:
  app:
    build:
      context: .
    volumes:
      - ./frontend/dist:/app/frontend/dist
    tmpfs:
      - /srv/media
    ports:
      - "8080:80"
    restart: always
    expose:
      - 8080

  nginx:
    image: nginx:alpine
    volumes:
      - ./config/nginx:/etc/nginx/conf.d/
      - ./config/certbot/conf:/etc/letsencrypt
      - ./config/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.90.0/24
