version: "3"
services:
  app:
    image: rickh94/title-page:19.10.4
    volumes:
      - completions:/completions
    tmpfs:
      - /srv/media
    restart: always
    networks:
      - titlepage

  nginx:
    image: nginx:alpine
    volumes:
      - ./data/nginx:/etc/nginx/conf.d/
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - app
    networks:
      - titlepage
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - titlepage
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  titlepage:

volumes:
  completions:
