version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./frontend/dist:/app/frontend/dist
#      - .:/app
    tmpfs:
      - /srv/media
    ports:
      - "8080:80"
    restart: always


networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.90.0/24
