version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "8080:80"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.90.0/24
