service: music-title-page

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
  stage: ${opt:stage, self:provider.stage}
  bucketName: ${self:custom.stage}-title-page-bucket-b38c91e9b


package:
  exclude:
    - ./Dockerfile
    - ./filled.html
    - ./test.html
    - ./test.pdf
    - yarn.lock
    - package.json

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1
  environment:
    BUCKET_NAME: ${self:custom.bucketName}


  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - Fn::GetAtt: [OutputBucket, Arn]
        - Fn::Join:
            - ''
            -
              - Fn::GetAtt: [OutputBucket, Arn]
              - '/*'


functions:
  create:
    handler: title_page.main
    events:
      - http:
          path: /
          method: post
          cors: true

resources:
  - ${file(s3-bucket.yml)}
